### PR TITLE
10.0.1 fix token exchange encoding

### LINKED ISSUE #12: [Internal] Add fix token button in userscript

### PR DESCRIPTION
**Pull request by Myrkie**
This patch will close #12 and addresses issues with token being set from the user script being not URL encoded resulting in failed token exchange with booth.pm when using user-script token button, this also addresses some issues with simple checks with the cookie if its null or white spaced.

### CODE REVIEW

File: BoothDownloader/src/Program.cs [hunk 1]
```diff
@@ -95,7 +97,7 @@ private static async Task<int> Main(string[] args)
             BoothConfig.Setup(configFile);
 
             #region First Boot
-            if (BoothConfig.Instance.Cookie == null)
+            if (string.IsNullOrWhiteSpace(BoothConfig.Instance.Cookie))
```
Comment (DubyaDude) [inline BoothDownloader/src/Program.cs:101]: I made this check null so string.Empty was essentially 'first boot complete, user didn't put in token'
This would start asking for a token every time.

File: BoothDownloader/src/Program.cs [hunk 2]
```diff
@@ -179,6 +181,9 @@ private static async Task<int> Main(string[] args)
                 if (BoothHttpClientManager.IsAnonymous)
                 {
                     LoggerHelper.GlobalLogger.LogError("Cannot download Paid Items with invalid cookie.");
+                    LoggerHelper.GlobalLogger.LogInformation("Exiting in 5 seconds...");
```
Comment (DubyaDude) [inline BoothDownloader/src/Program.cs]: People can add booth URLs along with a collection command. Not sure if you want to exit here, code at the end will end the program anyways for nothing to download, maybe move this exit pause down there.

**Review by DubyaDude — DISMISSED** [review]

File: BoothDownloader/src/Program.cs (hunk 1 above)
Comment (Myrkie) [reply BoothDownloader/src/Program.cs:101]: I changed it like this because if the token was null or failed token exchange, booth downloaded would set to the token to ""; and fail completely

File: BoothDownloader/src/Program.cs (hunk 2 above)
Comment (Myrkie) [reply BoothDownloader/src/Program.cs]: when using the url handler if the token was invalid it would still get to this part of the code but make it impossible to read the output, maybe just thread sleep for 5 seconds instead?

**Review by DubyaDude — APPROVED** [review]
